select a.CUST_CODE ,a.TOTAL_SPEND , a.TOTAL_VISIT, a.STD_TICKET_SIZE ,
a.DURING_SINCE_FIRST_PURCHASE,
a.DURING_SINCE_LAST_PURCHASE, 
a.LENGHT_OF_STAY,
a.AVERAGE_TIME_TO_EVENT,
MODE_BASKET_SIZE_TABLE.MODE_BASKET_SIZE  ,
MODE_SHOP_TIME_TABLE.MODE_SHOP_TIME  ,
MODE_SHOP_WEEKDAY_TABLE.MODE_WEEKDAY ,
MONTHLY_TABLE.AVERAGE_MONTHLY_VISIT,
MONTHLY_TABLE.AVERAGE_MONTHLY_SPEND,
MONTHLY_TABLE.STD_MONTHLY_SPEND,
MONTHLY_TABLE.STD_MONTHLY_VISIT
FROM
(
	SELECT  CUST_CODE , COUNT(DISTINCT BASKET_ID) AS TOTAL_VISIT,
    SUM(SPEND) AS TOTAL_SPEND, 
    AVG(SPEND) AS AVERAGE_TICKET_SIZE,
    STDDEV_POP(SPEND) AS STD_TICKET_SIZE,
    MAX(AGE) AS DURING_SINCE_FIRST_PURCHASE,
    MIN(AGE) AS DURING_SINCE_LAST_PURCHASE,
    MAX(AGE) - MIN(AGE) AS LENGHT_OF_STAY,
    (MAX(AGE) - MIN(AGE)) / COUNT(DISTINCT basket_id) AS AVERAGE_TIME_TO_EVENT
	FROM  
        (
            SELECT CUST_CODE , SPEND, SHOP_DATE , BASKET_ID , 
            DATE_DIFF (DATE'2008-07-06', PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)), DAY) as AGE,
            PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)) ,
            EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)))*100 + EXTRACT(MONTH FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) as SHOP_MONTH 
            FROM `supermarket.transactions_2stores` 
            WHERE CUST_CODE IS NOT NULL
        )
	    GROUP BY CUST_CODE
) AS a       
inner join
	(
	SELECT
	  CUST_CODE,  #Top number of BASKET_SIZE,
      (case 
	        when BASKET_SIZE = 'S' then 1 --S
	        when BASKET_SIZE = 'M' then 2 --M
	        else 3 end --L
	    ) as MODE_BASKET_SIZE,
	FROM (
	SELECT
	    DISTINCT CUST_CODE, BASKET_SIZE, ROW_NUMBER() OVER (PARTITION BY CUST_CODE ORDER BY COUNT(BASKET_SIZE) DESC) rn
	  FROM `supermarket.transactions_2stores`
	    WHERE CUST_CODE IS NOT NULL 
	  GROUP BY
	    CUST_CODE, BASKET_SIZE
	)
	WHERE
	  rn = 1
	) as  MODE_BASKET_SIZE_TABLE on a.CUST_CODE = MODE_BASKET_SIZE_TABLE.CUST_CODE

	inner join

	(
	SELECT
	  CUST_CODE, SHOP_TIME AS MODE_SHOP_TIME #Top number of SHOP_TIME
	FROM (
	SELECT
	    DISTINCT CUST_CODE, SHOP_TIME, ROW_NUMBER() OVER (PARTITION BY CUST_CODE ORDER BY COUNT(SHOP_TIME) DESC) rn_SHOP_TIME
	  FROM 
	(
		SELECT CUST_CODE ,
	    (case 
	        when shop_hour <= 11 then 1 --morning
	        when shop_hour between 12 and 16 then 2 --afternoon
	        else 3 end --evening
	    ) as SHOP_TIME,
	    FROM `supermarket.transactions_2stores`
	    WHERE CUST_CODE IS NOT NULL 
	)
	  
	  GROUP BY
	    CUST_CODE, SHOP_TIME
	)
	WHERE
	  rn_SHOP_TIME = 1

	) as MODE_SHOP_TIME_TABLE on a.CUST_CODE = MODE_SHOP_TIME_TABLE.CUST_CODE

	inner join 

	(
	SELECT
	  CUST_CODE, SHOP_WEEKDAY AS MODE_WEEKDAY #Top number of SHOP_WEEKDAY
	FROM (
	SELECT
	    DISTINCT CUST_CODE, SHOP_WEEKDAY, ROW_NUMBER() OVER (PARTITION BY CUST_CODE ORDER BY COUNT(SHOP_WEEKDAY) DESC) rn_SHOP_WEEKDAY
	  FROM `supermarket.transactions_2stores`
	    WHERE CUST_CODE IS NOT NULL 
	  GROUP BY
	    CUST_CODE, SHOP_WEEKDAY
	)
	WHERE
	  rn_SHOP_WEEKDAY = 1
	) as MODE_SHOP_WEEKDAY_TABLE on a.CUST_CODE = MODE_SHOP_WEEKDAY_TABLE.CUST_CODE

inner join 

(
	SELECT CUST_CODE, AVG(MONTHLY_VISIT) as AVERAGE_MONTHLY_VISIT, AVG(MONTHLY_SPEND) as AVERAGE_MONTHLY_SPEND , STDDEV_POP(MONTHLY_SPEND) as STD_MONTHLY_SPEND , STDDEV_POP(MONTHLY_VISIT) as STD_MONTHLY_VISIT 
	FROM (
		SELECT CUST_CODE, SHOP_MONTH , COUNT(*) as MONTHLY_VISIT , SUM(SPEND) as MONTHLY_SPEND
		FROM (
	         SELECT CUST_CODE, SPEND , 
	            DATE_DIFF (DATE'2008-07-06', PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)), DAY) as AGE,
	            PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)) ,
	            EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)))*100 + EXTRACT(MONTH FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) as SHOP_MONTH 
	            FROM `supermarket.transactions_2stores` 
	            WHERE CUST_CODE IS NOT NULL
	        )
		    GROUP BY CUST_CODE,SHOP_MONTH
		)
   GROUP BY CUST_CODE

) as MONTHLY_TABLE on a.CUST_CODE = MONTHLY_TABLE.CUST_CODE